### ISSUE TITLE
Locked REV Request

### ISSUE THREAD

**Issue by Tycondous** [rchain/Governance-Committee#10]
Good Afternoon,

I am writing to request that 248,159 REV that are locked in a Coinbase ETH/REV address be redirected to my REV address at the time of the first hard fork of the chain as I have fully paid for the REV and been told by Coinbase that I will never be receiving the private key to the address and to consider the tokens "lost".

To summarize what happened:
In September of 2007, I participated in the first Rchain token sale. I paid $50k and was to receive roughly 250k tokens.
An issue occurred where an initial address I had submitted for the RHOC to be sent to was a coinbase address. I changed this address at a later date as I filled out the online form to participate in the token sale, but the field reverted back to the coinbase address. I also originally wanted to purchase $100k of the sale, but had to reduce my amount which  led me to deduce what had happened re:the subscription site not updating (Emails 1 & 2 detail my conversations with the Coop and with Coinbase)
When the RHOC were sent they ended up at Coinbase and all but lost (my wife almost killed me), but given the integrity of the Coop and its leadership, they considered the RHOC burned (once I verified that coinbase was unlikely to return them) and provided me with 250k tokens to make me whole.
When a second token sale occured in 2018, I participated again, but also asked that I purchase the locked RHOC at Coinbase at the token sale price $0.35. I fully realized there was a risk to the RHOC never being recovered, but I regret nothing as the funds helped continue the development of Rchain (Email 3 details this request and the attached purchase agreement verifies I did indeed pay for the "unrecovered RHOC").
So that pretty much is it. I have verified that my coinbase ETH address (see Coinbase RHOC_REV Address) has an associated REV address (see Coinbase Locked Rev Address) with the locked REV (248,159) held within. I am requested that the REV at this address be voided at the upcoming hard fork and that the REV be reissued to my REV Wallet (Public Address: 1111m8K69WixFKCuws5L3S1pzS8qW1UWYURWJ1EXQepCtrZmNC8at).

I feel like I have concluded too many emails at this point as I am about to now, but it still holds: I have been and will continue to be a devoted supporter of Rchain and, I hope, you will be able to help me with this, but if not my support and devotion will not change.

Let me know if there is any further information I can provide.

Thank you,

C.M.
[Email 1 - Macgowan - Sept. Pre-Sale Issue Emails.pdf](https://github.com/rchain/Governance-Committee/files/6787454/Email.1.-.Macgowan.-.Sept.Pre-Sale.Issue.Emails.pdf)
[Email 2 - Coinbase - Lost Tokens Emails - Macgowan.pdf](https://github.com/rchain/Governance-Committee/files/6787455/Email.2.-.Coinbase.-.Lost.Tokens.Emails.-.Macgowan.pdf)
[Email 3 Macgowan - Emails to Ed and Lisa Rice asking for permission to purchase lost RHOC.pdf](https://github.com/rchain/Governance-Committee/files/6787456/Email.3.Macgowan.-.Emails.to.Ed.and.Lisa.Rice.asking.for.permission.to.purchase.lost.RHOC.pdf)
[Macgowan RHOC Purchase Agreement (fully executed) [Jul 17 2018].pdf](https://github.com/rchain/Governance-Committee/files/6787457/Macgowan.RHOC.Purchase.Agreement.fully.executed.Jul.17.2018.pdf)

**Comment by ian-bloom** [comment]
This checks out.
- The 248,159 RHOC at 0xdf02e8f9a889ccec06e3e61a865b4708e131dda1b7a3c7a594fc34d04173dab1 has remained in place since (Sep-07-2017 10:24:45 PM +UTC)
- At RChain genesis 248,159 REV were distributed to the corresponding address 11112rKj7LVy9R1LbA13VWAXkh6ddzmevQsSnHXZveTdR56RJu2of6

I propose that Co-op add the following adjustments at Hard-fork 1:

1. debit 248,159 REV  from 11112rKj7LVy9R1LbA13VWAXkh6ddzmevQsSnHXZveTdR56RJu2of6
2. credit 248,159 REV to 1111m8K69WixFKCuws5L3S1pzS8qW1UWYURWJ1EXQepCtrZmNC8at

**Comment by Tycondous** [comment]
Hello,

Let me know if there is anything else I can do to assist the Coop regarding
this issue.

Thanks again,

C.M.

Get Outlook for iOS <https://aka.ms/o0ukef>
------------------------------
*From:* ian-bloom ***@***.***>
*Sent:* Saturday, July 10, 2021 10:00:49 AM
*To:* rchain/Governance-Committee ***@***.***>
*Cc:* Tycondous ***@***.***>; Author ***@***.***>
*Subject:* Re: [rchain/Governance-Committee] Locked REV Request (#10)


This checks out.

   - The 248,159 RHOC at
   0xdf02e8f9a889ccec06e3e61a865b4708e131dda1b7a3c7a594fc34d04173dab1 has
   remained in place since (Sep-07-2017 10:24:45 PM +UTC)
   - At RChain genesis 248,159 REV were distributed to the corresponding
   address 11112rKj7LVy9R1LbA13VWAXkh6ddzmevQsSnHXZveTdR56RJu2of6

I propose that Co-op add the following adjustments at Hard-fork 1:

   1. debit 248,159 REV from
   11112rKj7LVy9R1LbA13VWAXkh6ddzmevQsSnHXZveTdR56RJu2of6
   2. credit 248,159 REV to
   1111m8K69WixFKCuws5L3S1pzS8qW1UWYURWJ1EXQepCtrZmNC8at

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rchain/Governance-Committee/issues/10#issuecomment-877642686>,
or unsubscribe

**Comment by SteveHenley** [comment]
Hold REV for 3 years in case someone submits a claim.

**Comment by 9rb** [comment]
In deference to maintaining the immutability of the block chain, The board has decided to not adjust block chain balances on claims of this nature through the hard fork process.  The Board resolution reads as below:

 Resolution: REV Distribution Policy at Hard Forks

On a motion by Greg Meredith, and seconded by Evan Jensen, it was moved to adopt the following policy:
If software authored by the Cooperative fails, resulting in REV being made inaccessible (burnt), at the nearest hard fork the Co-op will consider sweeping the balances of the burnt addresses into a Co-op escrow wallet; and in no other cases will the Cooperative modify REV distribution at a hard fork.

All board members present voted “Aye”.
The motion was carried unanimously.

Accordingly, the REV in this claim will stay as they are.

**Comment by Tycondous** [comment]
My claim is as clear as day. When I paid for the REV, I understood the risks but also assumed the coop would act appropriately when the opportunity came to make me whole. I have been told all along that this should not be a problem, what is the real issue? “Me too” complaints? Well, if someone has as clear a claim, then yes, you should make the whole, but I can’t imagine this is the case. Legal exposure? I don’t see how this raises the ever present level of legal exposure that exists.

So, to make a long story short, will someone directly tell me if I am going to be receiving the REV I paid for at this point when it can be released or not?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SteveHenley** [comment]
Already addressed
