### ISSUE TITLE
[ToD] Recover via Hard Fork 1, REV that should have been sent to staking

### ISSUE THREAD

**Issue by ian-bloom** [rchain/Governance-Committee#14]
**Description** 
Contractor attempted to deposit REV into the Co-op staking pool, but mistakenly sent to an address with no know private key. 

**Context**:  

- Block Explorer (revdefine.io) shows the errant [transaction](https://revdefine.io/#/blocks/393850c323279f68b999901db14d3a10837bbc2dbecfbb819bc3081e80180fd6/deploy/8dc6edec4c3572fb5fedcb74c7c9aeafad1802a11496073dbfff25adc5eb65ea2e6f84477375c912135dd1cade362b6cf60fa9920f2db37e7eb05b969d11bef91b) being sent to address 1111rsk1gRf3HJeon9kdndvJ5WQGqxmuRzfjBn8eTtxz5U9E1Yke6 instead of Co-op Staking pool 11112PvkcBG2NYXheMA3g8E6xiTNhBJguT9TncZPPmNfXg2Npb1kRU.
- Screenshot of my Discord communication with the contractor, where the error was discovered:
![Gov-Cmte-issue14-recover-stake](https://user-images.githubusercontent.com/3330502/125884892-b5167ff3-c138-42a1-a742-ea368e8378f7.png)
- Block Explorer (revdefine.io) [history](https://revdefine.io/#/revaccounts/1111rsk1gRf3HJeon9kdndvJ5WQGqxmuRzfjBn8eTtxz5U9E1Yke6) of the wallet receiving the errant transaction. Note that the balance has remain constant since the transaction and that the tokens were sent only 33 blocks before the contractor [successfully](https://revdefine.io/#/blocks/7312d312cff17c627889ba9cd32b221b75c1c8b767d70fa55580677f158dfbbe/deploy/37d2e131edf5f14ab8abbac4c0c4c7636fb24b3cbe458c31b84b5cbd95f1070b523f4dfff6f1b0c31acfd99f42e284c83d9ca66cf3812edd324da6bed7c124fe1c) deposited to the Co-op staking pool.

**Impact statement**: 
Moving REV from the errant wallet to the Co-op staking pool will not affect any other wallets.

**Benefits statement** 
Restoring the errant REV to the Co-op staking pool will recover REV which would otherwise remain unusable because the wallet private key is unknown.

**Implementation** 
Adjust the hard fork balances to debit 3499999.5 REV from 1111rsk1gRf3HJeon9kdndvJ5WQGqxmuRzfjBn8eTtxz5U9E1Yke6 REV and credit 3499999.5 REV to the Co-op staking pool 1111YVVUNB3VXV1VuJr1cQstfpP6CcCgaEDL6Vyordn5ynHTxiVEe will have no impact on other REV addresses.

**Time frame** 
To be implemented during Hard Fork 1

**Governance Bodies** to be advised:  e.g. Board, Finance and Audit, or Governance (in the case of a governance change)
Governance Committee

**Comment by 9rb** [comment]
In deference to maintaining the immutability of the block chain, The board has decided to not adjust block chain balances on claims of this nature through the hard fork process. The Board resolution reads as below:

Resolution: REV Distribution Policy at Hard Forks

On a motion by Greg Meredith, and seconded by Evan Jensen, it was moved to adopt the following policy:
If software authored by the Cooperative fails, resulting in REV being made inaccessible (burnt), at the nearest hard fork the Co-op will consider sweeping the balances of the burnt addresses into a Co-op escrow wallet; and in no other cases will the Cooperative modify REV distribution at a hard fork.

All board members present voted “Aye”.
The motion was carried unanimously.

Accordingly, the REV in this claim will stay as they are.

**Comment by SteveHenley** [comment]
Completed
