### ISSUE TITLE
[ToD] Request to transfer REV to another address

### ISSUE THREAD

**Issue by Isaac-DeFrain** [rchain/Governance-Committee#15]
# Request to transfer REV to another address

## Description

I attempted to keep REV/RHOC in a software ETH wallet, my hard drive crashed, and I lost the private key. I am requesting to have this REV sent to an address for which I have the private key.

- Currently
  - 23935.8685 REV at 1111DzyRE5GnFbxkuUrmcTXZfUSrtxQMVxWtHiAty8XrAPboALgRr
  - 0 REV at 11112gYhYXYWhRFsFj4DRssdpgQJMVvhLUURY8x91sFaLC3FoJLa5A

- Requesting
  - 0 REV at 1111DzyRE5GnFbxkuUrmcTXZfUSrtxQMVxWtHiAty8XrAPboALgRr
  - 23935.8685 REV at 11112gYhYXYWhRFsFj4DRssdpgQJMVvhLUURY8x91sFaLC3FoJLa5A

## Context

I was paid RHOC for technical writing work I did at the end of 2018 to the ETH address 0xc12040a912fcb2512b1ce6604b433f5c06a48981 (there are three transactions from Co-op ETH addresses to this one, link below). After this, I set up an ETH software wallet on a laptop (address 0x08942622ffcE89AD2f9090Ff7b7A39839e9fA031) and transferred all the RHOC (23935.8685) to this address (link below). This laptop's hard drive crashed some time in 2019 and the (now) REV were never moved from the corresponding REV address (1111DzyRE5GnFbxkuUrmcTXZfUSrtxQMVxWtHiAty8XrAPboALgRr) because I do not have the private key.

- Etherscan [Co-op to 0xc12040a912fcb2512b1ce6604b433f5c06a48981](https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0xc12040a912fcb2512b1ce6604b433f5c06a48981)

- Ehterscan [0xc12040a912fcb2512b1ce6604b433f5c06a48981 to 0x08942622ffcE89AD2f9090Ff7b7A39839e9fA031](https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0x08942622ffcE89AD2f9090Ff7b7A39839e9fA031)

- Revdefine [1111DzyRE5GnFbxkuUrmcTXZfUSrtxQMVxWtHiAty8XrAPboALgRr](https://revdefine.io/#/revaccounts/1111DzyRE5GnFbxkuUrmcTXZfUSrtxQMVxWtHiAty8XrAPboALgRr)

One can easily verify that the tokens originally came from Co-op controlled addresses and were paid to Isaac DeFrain at the supplied ETH address. One can also easily verify that the tokens have not moved from the REV address 1111DzyRE5GnFbxkuUrmcTXZfUSrtxQMVxWtHiAty8XrAPboALgRr.

I am humbly requesting that the REV at address 1111DzyRE5GnFbxkuUrmcTXZfUSrtxQMVxWtHiAty8XrAPboALgRr be transferred to address 11112gYhYXYWhRFsFj4DRssdpgQJMVvhLUURY8x91sFaLC3FoJLa5A (I have the private key for this address).

## Impact statement

Moving REV from this (dead) address to the requested address will not affect any other addresses.

## Benefits statement

Restoring the errant REV to the requested address will recover REV which would otherwise remain unusable because the wallet private key is unknown.

## Implementation

Adjust the hard fork balances to debit 23935.8685 REV from 1111DzyRE5GnFbxkuUrmcTXZfUSrtxQMVxWtHiAty8XrAPboALgRr and credit 23935.8685 REV to 11112gYhYXYWhRFsFj4DRssdpgQJMVvhLUURY8x91sFaLC3FoJLa5A will have no impact on other REV addresses.

## Time frame

To be implemented during Hard Fork 1

**Comment by 9rb** [comment]
In deference to maintaining the immutability of the block chain, The board has decided to not adjust block chain balances on claims of this nature through the hard fork process. The Board resolution reads as below:

Resolution: REV Distribution Policy at Hard Forks

On a motion by Greg Meredith, and seconded by Evan Jensen, it was moved to adopt the following policy:
If software authored by the Cooperative fails, resulting in REV being made inaccessible (burnt), at the nearest hard fork the Co-op will consider sweeping the balances of the burnt addresses into a Co-op escrow wallet; and in no other cases will the Cooperative modify REV distribution at a hard fork.

All board members present voted “Aye”.
The motion was carried unanimously.

Accordingly, the REV in this issue will stay as they are.
