### ISSUE TITLE
[ToD] Sweep REV from frozen RHOC multisig wallets into Co-op Escrow

### ISSUE THREAD

**Issue by ian-bloom** [rchain/Governance-Committee#16]
**Description** 
Initial wallet balances at RChain genesis reflected RHOC balances snapshotted at Ethereum block 9371743. Despite the Co-op's many announcements, some RHOC holders failed to remove their tokens from contract and multisig addresses prior to the snapshot, and they have not been able to access their REV on RChain mainnet.

**Context**:  
On April 6, 2021 Co-op board [resolution](https://github.com/rchain/board/tree/master/2021/04-06#resolution-sweep-frozen-rev) to sweep up the balances of inaccessible wallets during the coming hardfork.

**Impact** statement: 
Balances in REV addresses listed below will be transferred into an escrow wallet held by the Cooperative. The Co-op will oversee the redistribution of the escrowed REV.

**Benefits** statement 
Frozen REV will be unlocked so that Co-op can send it on to rightful owners.

**Implementation** 
As part of [Hard Fork 1](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fclick.convertkit-mail.com%2F4zuxp8o93esehde6mvsx%2Fkkhmh6h882r0ezal%2FaHR0cHM6Ly9naXRodWIuY29tL3JjaGFpbi9yY2hpcC1wcm9wb3NhbHMvaXNzdWVzLzQy&data=04%7C01%7C%7C2321b8ae7e164f85f1df08d94597ca44%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637617340505984365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kXtHaUVgTVkFJutTohhDgon1gex44IycxNyYobycLGM%3D&reserved=0), the wallets.txt file for the new fork will be adjusted. 

**Time frame** 
Saturday, July 17, 2021

**Governance Bodies** to be advised:  e.g. Board, Finance and Audit, or Governance (in the case of a governance change)
Co-op Board of Directors
Co-op Governance Committee

**Change Log** 

| Multisig addresses in block 9371743 snapshot | REV address                                            | 9371743 revlette | Current REV Balance |
| -------------------------------------------- | ------------------------------------------------------ | ---------------- | ------------------- |
| 0x8d12A197cB00D4747a1fe03395095ce2A5CC6819   | 1111Cb5gCywvPZRcaRyNJwTmjLBqmuBcd69yiFD7kWGBGTFuWQhsc  | 123888875532825  | 1,238,888.75532825  |
| 0xd35a2d8c651F3eba4F0a044DB961b5B0CCf68a2d   | 1111o3L7PsWJN9eauq4vRNKr5C7eqR1VvQ7kWCxuVrCt6QUbth6Jg  | 7.79E+15         | 0.00000000          |
| 0x6924d3ad691E7F641FFe1c95aa6297e4C10e5e86   | 11112cb7Y2VEn5wQLej8YCe51H2GnUdFzbmTuog3NKrhPjjo4CmaE7 | 278000           | 0.00278000          |
| 0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208   | 11112D4SBuovnUTvceojeGut1BWPESBrnNviUADZXHziL9mhQmJCMK | 33542049164080   | 335,420.49164080    |
| 0x9a2d163aB40F88C625Fd475e807Bbc3556566f80   | 1111szfAQYVPR89w6uuiaFBmCuZhSjtJqG79k2LvdAHtuqQLUNuSa  | 709000000000     | 7,090.00000000      |
| 0xbF29685856FAE1e228878DFB35B280C0adCC3B05   | 1111yyTrDHwp1E7eCvnXioqHo5XYPSRy9Sa39FRQuQb6zknsbKQMJ  | 113911827        | 1.13911827          |
| 0x168296bb09e24A88805CB9c33356536B980D3fC5   | 11112hAq6VEmDJAoopQQZoEomSWzodZMWgme4dGzwM7oeVP24fWBm4 | 1374504267036    | 0.00000000          |
| 0x21738172D0C17Fb5041AB5d7fe9B84914164482A   | 111127JbiyW4eMZJCr6QebBgkgvk97DGeygecHBcJd9mMiZ5EF3YnG | 400000000000     | 4,000.00000000      |
| 0x1cE7AE555139c5EF5A57CC8d814a867ee6Ee33D8   | 1111vFwkceSEPiDk6t9oC1ryFAPpGc8zAY83WMmPN9MXk9FYAcrHK  | 425736445456     | 4,257.36445456      |
| 0xb92102B5C12a1Bc4774ff53d720CB1660a842b94   | 11112FJN27C34UJ74QnQ9SWewSqfULP5mbHmYbiQfHJDJKdVQok58J | 200000000        | 2.00000000          |
| 0xF4342c8C8252c23C13E5Ce56EA51d9F24Ecf9012   | 11112sFQkSPhNRW89UKvXdDkpjy2oavHAwYQbM4ZjT5gJkKCv1AVBV | 10000000000      | 100.00000000        |
| 0xf8700dFfaBaC07A280069419298545387B4D5357   | 1111JrPrPHQ6ouxFtNB9AGj2U8HJrgx23XqtQRp8KgQ9W9NHrZC4X  | 100000000        | 1.00000000          |
| 0x980cAe4F2C7301D1D23FC709C379657C90D27D52   | 1111gnXjhGZM9F1XTQbwAM8XsgTQq2jCAa6Bu6mUWbjrue8ou6uzM  | 666833           | 0.00666833          |
| 0x85C5c26DC2aF5546341Fc1988B9d178148b4838B   | 1111fSRL2QtE6u4XW7631oEYCzrm5FC1RmXDKn1myC5vA1PYXQv4x  | 97442948585      | 974.42948585        |
| 0xB5ed18405949DB4aBC029077533115f63D80996f   | 11112wPvMS7t9uVy52BtVPFt9a1ScVhrcHLHThwNuKbJnqiZR7VgMx | 6076000          | 0.06076000          |
| 0xdC36CbE88eFD1b4Ef5cDcdbe74f0B28cd1e23D12   | 1111PEw4wKQLaWBpwVdQbnv5KYE4hXAogXeLySTxHDxRuaPzuZNG1  | 920000           | 0.00920000          |
| 0xbF45F4280Cfbe7C2D2515A7D984B8c71c15E82B7   | 11112BLVsPRTAJkb5sBQna9hR2q5isnjitqp48UqAcDJoN6agQoC6e | 492105856        | 4.92105856          |
| 0xFCb733335456AACB010b3ba2f6270C83E849eCC3   | 11112JjWJttFn7jTvHiiuuGbE1FHWPabP6KFHo1RjxCoxSBBH8Edhp | 23055366800000   | 230,553.66800000    |
| 0xB4bCCD6095D9C0fbDf93c06c260384fb76c41ef5   | 11112arYYZNJv6fEx4kkzEitrQS951xnuY311BRWjkhe3wqR68UVot | 199214           | 0.00199214          |
| 0x4D71b91D46fA7247870804601E53AD9330CC7dCe   | 111129rRaQtqHdtkmryMVVhsQNXjSPdbNYyhvyuo8uqtsEMBRXT4fg | 1190622          | 0.01190622          |
| 0x04F062809B244e37e7fDC21D9409469c989C2342   | 11114n2ABnLj4MPg6p7K21pLTo2Ba7GwNiHQoFSWbMehAjXQDuXSh  | 28089142976      | 280.89142976        |
| 0x38c6A68304cdEfb9BEc48BbFaABA5C5B47818bb2   | 11112bo93nUSFbwPyBac76nNMjvUZku6Sn3PZfg45X39JRH1TdHc2E | 500000000000     | 5,000.00000000      |
| 0xbAd7653bc486c44FBeafa23FdEd6b3F3112D321C   | 111123DVqkXrwFrVMhcZeEKQYZtyXUDX4apZoU5e7bKDnFxo86MMzH | 6000             | 0.00006000          |
| 0x6Ab7b546C392f62a8E1c4d483241FF605369f4de   | 1111ZfHnsAN6WCAdhgmd9KqxZQq7aSzs9FXYUdkYpsr5EFPdxb5sT  | 600000           | 0.00600000          |
| 0x2af47a65da8CD66729b4209C22017d6A5C2d2400   | 1111266XWAw5tsFLYFMaKvJx8NFxG8fCM8KjQpJCPCFZzETP1u1RoL | 200000000000     | 2,000.00000000      |
| 0x1c73D4Ff97b9c8299F55D3b757B70979Ee718754   | 1111sLSFKsphzvzd1DEFM5ApC7Rm7gLyLwWfBti7AKLiamNg2ENfY  | 2.75E+16         | 0.00000000          |
| 0x287550958BE9D74d7f7152C911BA0b71801153A8   | 1111ZTC3usfohE81V9DLr1z1aV2B4iLEPtfuJFeaUtgxxaJLNyXBv  | 3.12E+15         | 0.00000000          |
| 0x821aA521Ecba3f4fdef89cBe1F468636e858d90d   | 1111gPMSXwruJo1YwjE4tGSoHKcAKNdCxDsxwgrs4E8rH2L4gVamn  | 400000000000000  | 0.00000000          |
| 0x097D850094aF2d8b50C099414fc0953AeeFe5022   | 111155LWAZmK3z954xXdgGL4NTSr3hfSA6SF3a9s3RMHrnm1kKWmC  | 802059300000     | 8,020.59300000      |
| 0x394e524b47A3AB3D3327f7fF6629dC378c1494a3   | 1111Mez7uA98KLUDTUiHX5YrwkZQLvKiKZAyxuBNnTZ1wqBT9taZZ  | 851202141        | 8.51202141          |
| 0x14a4617C7A95046546541973797e44df7770f837   | 1111CKhxcZBYpdm5P1iqJBsZdYPwHjnN8o4PPAW86c6qwyZWw81Z5  | 900000           | 0.00900000          |
| 0x8ab7fdE4B32e9Bd66734e550A145aeB12822681D   | 1111PnyhUaDdWLRaBwAJCCTwuYhQ2CgRduzBNUKvhKzyNHi6BqYYt  | 1500000000       | 15.00000000         |
| 0xf15230Cba5B211B7Cb6A4ae7cFc5a84e9cb6865d   | 11112GtJZAJX88jiGB72Keb6pbSwUpve8ZbhRLoTBpaWrMSqK8A3gW | 1.42E+15         | 0.00000000          |
| 0xd52Bc4fE5DA20BA35f25b38581c805B165211f99   | 1111EuHdop7WXbc5YmJ32W3346pJQ5iaJ34TCQPotS5UCB6FZeWAk  | 237857           | 0.00237857          |
| 0x82da82DBe384736e4Dd95615D8036Cc472773F5A   | 11112CWQn4iB5wYhLZfcJfTNB1KRkDdKX3qRdvwYEW243QMLyCwQtV | 200001           | 0.00200001          |
| 0xcf25EbD54120cF2e4137Fab0A91a7f7403A5DEbF   | 1111mVkwH4cNqGFJUVexm547sTDqxGiHT5V7Hgnmbahv2YVJ7Ho12  | 2992750000       | 29.92750000         |
| 0x409B512e1cf94500877C5353B2a0C13B2d24914F   | 11117WyybqVatycVNWkKw1ByoDUqT4784ShDgpgJdJA1cEvjA9XvT  | 89787            | 0.00089787          |
| 0x8018280076d7fA2cAa1147e441352E8a89e1DDbe   | 111128uSxdK5XQcPy9o4XWZgoC8SheiBLEiwbXRa8AsWKK3hMXiLbn | 1                | 0.00000001          |
| 0xCB60D600160D005845Ec999f64266D5608fd8943   | 11114yAC6A8UMhej5TcrSEUMWkmhigrjUKRDNw3TAvWoUpyy7eQGe  | 334000000        | 3.34000000          |
|                                              |                                                        |                  |                     |
|                                              |                                                        |                  | 1,836,652.14668061  |

**Comment by ian-bloom** [comment]
Balances from these (frozen) wallets will be swept in to the Co-op Escrow wallet 11112YnRy3SPFwJHkTeagQNrruEUTBUxQV7YPm5zomFGKiK1Z62VHg

**Comment by SteveHenley** [comment]
Completed
