### ISSUE TITLE
Monetary Policy (IoB 2020-1)

### ISSUE THREAD

**Issue by ian-bloom** [rchain/Governance-Committee#5]
## Monetary Policy

Item of Business (IoB) 2020-1 has been approved by 3 Co-op directors and will be included on the 2020 Annual Meeting ballot.

#### IoB 2020-1 (Monetary Policy)
> **Now that the mainnet has been operational for several months, the membership resolves that the board of directors should create and adopt an appropriate new monetary policy based on network security considerations such as: [Gov-Cmte Issue #5](https://github.com/rchain/Governance-Committee/issues/5)**

### Considerations

1. Restrictions on REV handling by coop management should not be so restrictive as to constrain day to day business operations and needs of the cooperative.
2. Network security must be ensured with appropriate staking policies such that
   1. sufficient stake will always be available to secure the network
   2. the stake distribution over time is such that sufficient reaction time is available to the coop to identify trends in staking and react appropriately to the resulting network security risks.
   3. the stake distribution over time is such that sufficient reaction time is available to the coop to identify trends in staking and react appropriately to the resulting network security risks.
   4. the staking rules allow sufficient flexibility for those staking, including the ability to stake at any time and the ability to free up some of the stake on a regular basis without it being locked up for a long time
   5. the staking scheme is sustainable and steady irrespective of fluctuations in the market price of the REV (typical in crypto token markets) and does not lead to draining a large amount of stake at any point.
   6. the cost of maintaining network security is shared by all.

**Comment by jimscarver** [comment]
eth token economics of [EIP 1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md) is worth reviewing in considering rchain monetary policy https://youtu.be/MGemhK9t44Q

**Comment by SteveHenley** [comment]
Membership vote was completed.
