### ISSUE TITLE
RHOC to REV issue

### ISSUE THREAD

**Issue by PitsGitHub** [rchain/Governance-Committee#7]
Hello Governance-Committee,

i need some support with accessing my REV tokens.

I currently hold 14975 RHOC in my MEW (MyEtherWallet)

Here is proof of that:
4975 RHOC transfer to MEW
https://ethplorer.io/tx/0x13f46d92f1d4a4275cf9579decd7a5016af98e068b91fb050ea9e36934aa5ceb#pageSize=50
10000 RHOC transfer to MEW
https://ethplorer.io/tx/0x8499699ac098153af4a2448e4a1f392633ba37f20eb00145d9b4dd918ef593e3#pageSize=50
Under revdefine i only see 10000 detected REV
https://revdefine.io/#/revaccounts/1111uaZise8tinD96GGboffwm35BMHNm88cmsftTzCUBmAoCsQq9h

I am not familiar with coding or scripts so i do not know how to confirm the missing 4975 RHOC
I also created an account here https://myrchainwallet.com/
Unfortunately i am not sure how to move my existing REV into that wallet to make them accessable.

Can you please assist me in this matter of accessing my REV in a way that i can transfer them?

**Comment by jimscarver** [comment]
rhoc obtained after mainnet launch is entitled to no REV
![image](https://user-images.githubusercontent.com/3037201/118382052-30f9f280-b5bf-11eb-910c-430ba7dd2a21.png)
https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0x8341a22BFb62F529264590d9330684B79e839311
