### ISSUE TITLE
[ToD] RHOC in a multisig wallet 

### ISSUE THREAD

**Issue by Shelby1256** [rchain/Governance-Committee#8]
I am opening this topic after reading the answers that “jimscaver” has given on Discord to other users who have experienced problems similar to mine, hereafter following his advice.

I purchased RHOC tokens on the exchange “Kucoin.com” in 2018, in two different occasions, moving then the purchased tokens on my multisig ETH wallet. In 2019 I have transferred the tokens on the exchange “Hotbit.io”, and then after some weeks I moved those tokens back to my multisig ETH wallet. My tokens were in my multisig ETH wallet at the moment of the swap from RHOC to REV. I didn’t receive my REV tokens because of this.

I am reporting some answers that “jimscaver” has given on Discord to users that experienced a similar issue with a multisig wallet: 

![image](https://user-images.githubusercontent.com/83900236/117563648-93c32980-b0a7-11eb-8c64-816ea48fe097.png)

![image](https://user-images.githubusercontent.com/83900236/117563650-99207400-b0a7-11eb-94b0-3a128cd11cd2.png)

This is the address of my multisig ETH wallet in which I received my RHOC tokens: 

https://etherscan.io/address/0x097d850094af2d8b50c099414fc0953aeefe5022

This is the same wallet that was holding the RHOC tokens at the moment of the swap.

Here a  screenshot of the transactions described earlier on my wallet with the RHOC tokens:

![Screen Shot 05-08-21 at 05 21 PM](https://user-images.githubusercontent.com/83900236/117563672-c66d2200-b0a7-11eb-9bfb-f529975a923e.PNG)

Here a screenshot of the withdrawals done on Kucoin of my RHOC tokens to my multisig wallet:

![image](https://user-images.githubusercontent.com/83900236/117563696-dc7ae280-b0a7-11eb-8c4a-dd9d92fdf337.png)

If you need a proof of the ownership of the ETH address associated to the multisig wallet mentioned earlier, in which the RHOC tokens are held, I can send a small transaction to Jim or another member of the team.

If you need further information, do let me know. 

I am looking forward to receiving an answer about this, confident that we will find a way to solve this issue positively.

Thank You in advance

**Comment by ian-bloom** [comment]
@Shelby1256, I propose that the Co-op honor your claim if you can prove ownership of 0x097d850094af2d8b50c099414fc0953aeefe5022. Please supply an address where you would like to receive the REV tokens, and include the address in the message to be signed using eth-sign. 

Verify your ownership of 0x097d850094af2d8b50c099414fc0953aeefe5022 by [signing](https://cryptonomica.net/eth-sign/#!/) the following message and then pasting the resulting signature in this issue.

> I am the owner of 0x097d850094af2d8b50c099414fc0953aeefe5022 and I request RChain Cooperative to send 8,020.593 REV to (1111......) because my genesis tokens were frozen in a multisig contract.

**Comment by ian-bloom** [comment]
0x097d850094af2d8b50c099414fc0953aeefe5022 is a __multisig__ wallet that was identified in the initial RHOC [snapshot](https://github.com/rchain/rchain/blob/dev/wallets_RHOC_BLOCK-9371743.txt#L5787) from which the RChain REV genesis wallet addresses and balances were derived.

RChain Co-op April 6, 2021 Board of Directors [resolved](https://github.com/rchain/board/tree/master/2021/04-06#resolution-sweep-frozen-rev) to sweep the balances of multisig RHOC addresses such as this one into an escrow wallet during the coming "[Hard Fork 1](https://github.com/rchain/rchip-proposals/issues/42)".

We are waiting for @Shelby1256 to [prove](https://github.com/rchain/Governance-Committee/issues/8#issuecomment-877651798) ownership of 0x097d850094af2d8b50c099414fc0953aeefe5022.

**Comment by 9rb** [comment]
The claimant has not provided the proof requested above. 

In addition, In deference to maintaining the immutability of the block chain, The board has decided to not adjust block chain balances on claims of this nature through the hard fork process. The Board resolution reads as below:

Resolution: REV Distribution Policy at Hard Forks

On a motion by Greg Meredith, and seconded by Evan Jensen, it was moved to adopt the following policy:
If software authored by the Cooperative fails, resulting in REV being made inaccessible (burnt), at the nearest hard fork the Co-op will consider sweeping the balances of the burnt addresses into a Co-op escrow wallet; and in no other cases will the Cooperative modify REV distribution at a hard fork.

All board members present voted “Aye”.
The motion was carried unanimously.

**Comment by dckc** [comment]
@9rb did you mean to close this? If not, what is left to do?
